# Generated by Django 5.0.4 on 2024-05-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apis', '0002_homefollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefollow',
            name='hashtag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homefollow',
            name='image',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
